//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("petloveModel", "fk_tb_animal_tb_racas1", "tb_racas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PetLoveWeb.Banco.tb_racas), "tb_animal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PetLoveWeb.Banco.tb_animal), true)]
[assembly: EdmRelationshipAttribute("petloveModel", "fk_tb_animal_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PetLoveWeb.Banco.tb_usuario), "tb_animal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PetLoveWeb.Banco.tb_animal), true)]
[assembly: EdmRelationshipAttribute("petloveModel", "fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PetLoveWeb.Banco.tb_usuario), "tb_favoritos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PetLoveWeb.Banco.tb_favoritos), true)]

#endregion

namespace PetLoveWeb.Banco
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class petloveEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new petloveEntities object using the connection string found in the 'petloveEntities' section of the application configuration file.
        /// </summary>
        public petloveEntities() : base("name=petloveEntities", "petloveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new petloveEntities object.
        /// </summary>
        public petloveEntities(string connectionString) : base(connectionString, "petloveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new petloveEntities object.
        /// </summary>
        public petloveEntities(EntityConnection connection) : base(connection, "petloveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_animal> tb_animal
        {
            get
            {
                if ((_tb_animal == null))
                {
                    _tb_animal = base.CreateObjectSet<tb_animal>("tb_animal");
                }
                return _tb_animal;
            }
        }
        private ObjectSet<tb_animal> _tb_animal;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_favoritos> tb_favoritos
        {
            get
            {
                if ((_tb_favoritos == null))
                {
                    _tb_favoritos = base.CreateObjectSet<tb_favoritos>("tb_favoritos");
                }
                return _tb_favoritos;
            }
        }
        private ObjectSet<tb_favoritos> _tb_favoritos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_fotos> tb_fotos
        {
            get
            {
                if ((_tb_fotos == null))
                {
                    _tb_fotos = base.CreateObjectSet<tb_fotos>("tb_fotos");
                }
                return _tb_fotos;
            }
        }
        private ObjectSet<tb_fotos> _tb_fotos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_racas> tb_racas
        {
            get
            {
                if ((_tb_racas == null))
                {
                    _tb_racas = base.CreateObjectSet<tb_racas>("tb_racas");
                }
                return _tb_racas;
            }
        }
        private ObjectSet<tb_racas> _tb_racas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_usuario> tb_usuario
        {
            get
            {
                if ((_tb_usuario == null))
                {
                    _tb_usuario = base.CreateObjectSet<tb_usuario>("tb_usuario");
                }
                return _tb_usuario;
            }
        }
        private ObjectSet<tb_usuario> _tb_usuario;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_animal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_animal(tb_animal tb_animal)
        {
            base.AddObject("tb_animal", tb_animal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_favoritos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_favoritos(tb_favoritos tb_favoritos)
        {
            base.AddObject("tb_favoritos", tb_favoritos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_fotos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_fotos(tb_fotos tb_fotos)
        {
            base.AddObject("tb_fotos", tb_fotos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_racas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_racas(tb_racas tb_racas)
        {
            base.AddObject("tb_racas", tb_racas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_usuario(tb_usuario tb_usuario)
        {
            base.AddObject("tb_usuario", tb_usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="petloveModel", Name="tb_animal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_animal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_animal object.
        /// </summary>
        /// <param name="iDAnimal">Initial value of the IDAnimal property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="categoria">Initial value of the Categoria property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="iDRaca">Initial value of the IDRaca property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static tb_animal Createtb_animal(global::System.Int32 iDAnimal, global::System.String nome, global::System.String categoria, global::System.String sexo, global::System.Int32 iDUsuario, global::System.Int32 iDRaca, global::System.Single latitude, global::System.Single longitude)
        {
            tb_animal tb_animal = new tb_animal();
            tb_animal.IDAnimal = iDAnimal;
            tb_animal.Nome = nome;
            tb_animal.Categoria = categoria;
            tb_animal.Sexo = sexo;
            tb_animal.IDUsuario = iDUsuario;
            tb_animal.IDRaca = iDRaca;
            tb_animal.Latitude = latitude;
            tb_animal.Longitude = longitude;
            return tb_animal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAnimal
        {
            get
            {
                return _IDAnimal;
            }
            set
            {
                if (_IDAnimal != value)
                {
                    OnIDAnimalChanging(value);
                    ReportPropertyChanging("IDAnimal");
                    _IDAnimal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDAnimal");
                    OnIDAnimalChanged();
                }
            }
        }
        private global::System.Int32 _IDAnimal;
        partial void OnIDAnimalChanging(global::System.Int32 value);
        partial void OnIDAnimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Categoria
        {
            get
            {
                return _Categoria;
            }
            set
            {
                OnCategoriaChanging(value);
                ReportPropertyChanging("Categoria");
                _Categoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Categoria");
                OnCategoriaChanged();
            }
        }
        private global::System.String _Categoria;
        partial void OnCategoriaChanging(global::System.String value);
        partial void OnCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Nascimento
        {
            get
            {
                return _Nascimento;
            }
            set
            {
                OnNascimentoChanging(value);
                ReportPropertyChanging("Nascimento");
                _Nascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nascimento");
                OnNascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Nascimento;
        partial void OnNascimentoChanging(Nullable<global::System.DateTime> value);
        partial void OnNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                if (_IDUsuario != value)
                {
                    OnIDUsuarioChanging(value);
                    ReportPropertyChanging("IDUsuario");
                    _IDUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuario");
                    OnIDUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDRaca
        {
            get
            {
                return _IDRaca;
            }
            set
            {
                if (_IDRaca != value)
                {
                    OnIDRacaChanging(value);
                    ReportPropertyChanging("IDRaca");
                    _IDRaca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDRaca");
                    OnIDRacaChanged();
                }
            }
        }
        private global::System.Int32 _IDRaca;
        partial void OnIDRacaChanging(global::System.Int32 value);
        partial void OnIDRacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Single _Latitude;
        partial void OnLatitudeChanging(global::System.Single value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Single _Longitude;
        partial void OnLongitudeChanging(global::System.Single value);
        partial void OnLongitudeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_animal_tb_racas1", "tb_racas")]
        public tb_racas tb_racas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_racas>("petloveModel.fk_tb_animal_tb_racas1", "tb_racas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_racas>("petloveModel.fk_tb_animal_tb_racas1", "tb_racas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_racas> tb_racasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_racas>("petloveModel.fk_tb_animal_tb_racas1", "tb_racas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_racas>("petloveModel.fk_tb_animal_tb_racas1", "tb_racas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_animal_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_animal_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_animal_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_animal_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("petloveModel.fk_tb_animal_tb_usuario1", "tb_usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="petloveModel", Name="tb_favoritos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_favoritos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_favoritos object.
        /// </summary>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="iDAnimalFavorito">Initial value of the IDAnimalFavorito property.</param>
        public static tb_favoritos Createtb_favoritos(global::System.Int32 iDUsuario, global::System.Int32 iDAnimalFavorito)
        {
            tb_favoritos tb_favoritos = new tb_favoritos();
            tb_favoritos.IDUsuario = iDUsuario;
            tb_favoritos.IDAnimalFavorito = iDAnimalFavorito;
            return tb_favoritos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                if (_IDUsuario != value)
                {
                    OnIDUsuarioChanging(value);
                    ReportPropertyChanging("IDUsuario");
                    _IDUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuario");
                    OnIDUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDAnimal
        {
            get
            {
                return _IDAnimal;
            }
            set
            {
                OnIDAnimalChanging(value);
                ReportPropertyChanging("IDAnimal");
                _IDAnimal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAnimal");
                OnIDAnimalChanged();
            }
        }
        private Nullable<global::System.Int32> _IDAnimal;
        partial void OnIDAnimalChanging(Nullable<global::System.Int32> value);
        partial void OnIDAnimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAnimalFavorito
        {
            get
            {
                return _IDAnimalFavorito;
            }
            set
            {
                OnIDAnimalFavoritoChanging(value);
                ReportPropertyChanging("IDAnimalFavorito");
                _IDAnimalFavorito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAnimalFavorito");
                OnIDAnimalFavoritoChanged();
            }
        }
        private global::System.Int32 _IDAnimalFavorito;
        partial void OnIDAnimalFavoritoChanging(global::System.Int32 value);
        partial void OnIDAnimalFavoritoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="petloveModel", Name="tb_fotos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_fotos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_fotos object.
        /// </summary>
        /// <param name="iDFoto">Initial value of the IDFoto property.</param>
        /// <param name="foto">Initial value of the Foto property.</param>
        /// <param name="iDAnimal">Initial value of the IDAnimal property.</param>
        public static tb_fotos Createtb_fotos(global::System.Int32 iDFoto, global::System.Byte[] foto, global::System.Int32 iDAnimal)
        {
            tb_fotos tb_fotos = new tb_fotos();
            tb_fotos.IDFoto = iDFoto;
            tb_fotos.Foto = foto;
            tb_fotos.IDAnimal = iDAnimal;
            return tb_fotos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFoto
        {
            get
            {
                return _IDFoto;
            }
            set
            {
                if (_IDFoto != value)
                {
                    OnIDFotoChanging(value);
                    ReportPropertyChanging("IDFoto");
                    _IDFoto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFoto");
                    OnIDFotoChanged();
                }
            }
        }
        private global::System.Int32 _IDFoto;
        partial void OnIDFotoChanging(global::System.Int32 value);
        partial void OnIDFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAnimal
        {
            get
            {
                return _IDAnimal;
            }
            set
            {
                OnIDAnimalChanging(value);
                ReportPropertyChanging("IDAnimal");
                _IDAnimal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAnimal");
                OnIDAnimalChanged();
            }
        }
        private global::System.Int32 _IDAnimal;
        partial void OnIDAnimalChanging(global::System.Int32 value);
        partial void OnIDAnimalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="petloveModel", Name="tb_racas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_racas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_racas object.
        /// </summary>
        /// <param name="iDRaca">Initial value of the IDRaca property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static tb_racas Createtb_racas(global::System.Int32 iDRaca, global::System.String nome, global::System.String tipo)
        {
            tb_racas tb_racas = new tb_racas();
            tb_racas.IDRaca = iDRaca;
            tb_racas.Nome = nome;
            tb_racas.Tipo = tipo;
            return tb_racas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDRaca
        {
            get
            {
                return _IDRaca;
            }
            set
            {
                if (_IDRaca != value)
                {
                    OnIDRacaChanging(value);
                    ReportPropertyChanging("IDRaca");
                    _IDRaca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDRaca");
                    OnIDRacaChanged();
                }
            }
        }
        private global::System.Int32 _IDRaca;
        partial void OnIDRacaChanging(global::System.Int32 value);
        partial void OnIDRacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_animal_tb_racas1", "tb_animal")]
        public EntityCollection<tb_animal> tb_animal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_animal>("petloveModel.fk_tb_animal_tb_racas1", "tb_animal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_animal>("petloveModel.fk_tb_animal_tb_racas1", "tb_animal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="petloveModel", Name="tb_usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_usuario object.
        /// </summary>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="usuario">Initial value of the Usuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static tb_usuario Createtb_usuario(global::System.Int32 iDUsuario, global::System.String usuario, global::System.String nome, global::System.String email, global::System.String senha)
        {
            tb_usuario tb_usuario = new tb_usuario();
            tb_usuario.IDUsuario = iDUsuario;
            tb_usuario.Usuario = usuario;
            tb_usuario.Nome = nome;
            tb_usuario.Email = email;
            tb_usuario.Senha = senha;
            return tb_usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                if (_IDUsuario != value)
                {
                    OnIDUsuarioChanging(value);
                    ReportPropertyChanging("IDUsuario");
                    _IDUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuario");
                    OnIDUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_animal_tb_usuario1", "tb_animal")]
        public EntityCollection<tb_animal> tb_animal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_animal>("petloveModel.fk_tb_animal_tb_usuario1", "tb_animal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_animal>("petloveModel.fk_tb_animal_tb_usuario1", "tb_animal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("petloveModel", "fk_tb_usuario_has_tb_animal_tb_usuario", "tb_favoritos")]
        public tb_favoritos tb_favoritos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_favoritos>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_favoritos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_favoritos>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_favoritos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_favoritos> tb_favoritosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_favoritos>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_favoritos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_favoritos>("petloveModel.fk_tb_usuario_has_tb_animal_tb_usuario", "tb_favoritos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
